# Generated by Django 6.0.1 on 2026-01-16 18:57

import ingest.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default=ingest.enums.Status["PENDING"],
                        max_length=20,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("parsing", "parsing"),
                            ("uploading", "uploading"),
                            ("done", "done"),
                        ],
                        default=ingest.enums.Step["QUEUED"],
                        max_length=20,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
