"""
Django settings for multi_agent_for_education_app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qc1#mm^)5o_0i8bx#4i#o)#rr67uc=y7zjw)s$r-9w*mgtm+nk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django_daisy",
    "django.contrib.admin",
    "django.contrib.humanize",  # Required
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_neomodel",
    # Local Apps
    "ingest",
    "knowledge",
    "agents",
    "analytics",
    "accounts",
    "django_huey",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "multi_agent_for_education_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "multi_agent_for_education_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Admin Panel Daisy

DAISY_SETTINGS = {
    # Branding
    "SITE_TITLE": "Multi-Agent for Education",
    "SITE_HEADER": "Administration",
    "INDEX_TITLE": "Hi, welcome to your dashboard",
    "SITE_LOGO": "/static/admin/img/daisyui-logomark.svg",
    # Customization
    "EXTRA_STYLES": [],  # Additional CSS files
    "EXTRA_SCRIPTS": [],  # Additional JS files
    "LOAD_FULL_STYLES": False,  # Load complete DaisyUI library
    "SHOW_CHANGELIST_FILTER": False,  # Auto-open filter sidebar
    "DONT_SUPPORT_ME": False,  # Hide GitHub link
    "SIDEBAR_FOOTNOTE": "",  # Custom sidebar footer text
    # Theme Configuration
    "DEFAULT_THEME": None,  # e.g., 'corporate', 'dark'
    "DEFAULT_THEME_DARK": None,  # Dark mode default
    "SHOW_THEME_SELECTOR": True,  # Show/hide theme dropdown
    "THEME_LIST": [
        {"name": "Light", "value": "light"},
        {"name": "Dark", "value": "dark"},
        # Add custom themes...
    ],
    # Third-Party App Customization
    "APPS_REORDER": {
        "auth": {
            "icon": "fa-solid fa-person-military-pointing",
            "name": "Authentication",
            "hide": False,
            "divider_title": "Auth",
        },
    },
}

AUTH_USER_MODEL = "accounts.User"

# Google Gemini API Key
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")

# Neo4j Configuration
NEO4J_URI = os.environ.get("NEO4J_URI")
NEO4J_USERNAME = os.environ.get("NEO4J_USERNAME")
NEO4J_PASSWORD = os.environ.get("NEO4J_PASSWORD")

# Django Huey Configuration
DJANGO_HUEY = {
    "default": "main",
    "queues": {
        "main": {
            "huey_class": "huey.SqliteHuey",
            "name": "default",
            "filename": BASE_DIR / "huey.sqlite3",
            "results": True,
            "store_none": False,
            "immediate": False,
            "utc": True,
        }
    },
}
